/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Decision } from "./Decision";
import { DecisionCountArgs } from "./DecisionCountArgs";
import { DecisionFindManyArgs } from "./DecisionFindManyArgs";
import { DecisionFindUniqueArgs } from "./DecisionFindUniqueArgs";
import { DeleteDecisionArgs } from "./DeleteDecisionArgs";
import { DecisionService } from "../decision.service";
@graphql.Resolver(() => Decision)
export class DecisionResolverBase {
  constructor(protected readonly service: DecisionService) {}

  async _decisionsMeta(
    @graphql.Args() args: DecisionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Decision])
  async decisions(
    @graphql.Args() args: DecisionFindManyArgs
  ): Promise<Decision[]> {
    return this.service.decisions(args);
  }

  @graphql.Query(() => Decision, { nullable: true })
  async decision(
    @graphql.Args() args: DecisionFindUniqueArgs
  ): Promise<Decision | null> {
    const result = await this.service.decision(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Decision)
  async deleteDecision(
    @graphql.Args() args: DeleteDecisionArgs
  ): Promise<Decision | null> {
    try {
      return await this.service.deleteDecision(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
